- README.md
> Fixed python version in README.md

- client.py
Add t-yosemite-r7-{108, 139, 146, 381} to ssh_unresponsive issues and t-yosemite-r7-072 to other_issues
> Add t-yosemite-r7-{108, 139, 146, 381} to ssh_unresponsive issues and t-yosemite-r7-072 to other_issues

- client.py
Remove  T-W1064-MS-{046...180} and {581...600}
> Update the Windows Loaners List

- client.py
added a few unresponsive and stdio yosemite machines
> added a few unresponsive and stdio yosemite machines

- client.py
Add: T-W1064-MS-116,
Delete: T-W1064-MS-151, t-yosemite-r7-{039, 045, 087, 108, 142, 161, 229, 241, 284, 306, 315, 349, 378, 433}
> Update client.py for Osx and Win

- client.py
updatded few info boxes, removed special case for win, removed OSX: 457
> Removed OSX: 457

- client.py
Add T-W1064-MS-160 to PXE issues
> Add T-W1064-MS-160 to PXE issues

- client.py
Remove T-W1064-MS-160.Problem has been fixed
> Remove T-W1064-MS-160.Problem has been fixed

- client.py
> remove  t-yosemite-r7-130

- client.py
* Add the entire FQDN to the machine (for easy SSH)
* Re-enable MDC2 range for Win10
* Add warning to MDC2 machines that are being outputed, to be shut down.
> Updated how Win10 output is handled

- client.py
Fixed FQDN for Windows moonshots
> Fixed FQDNs

- client.py
added T-W1064-MS-020 currently it has a share deploy issue
> added T-W1064-MS-020

- client.py
add T-W1064-MS-028 after reboot and reimage machine is still missing from taskcluster
> Add T-W1064-MS-028

- client.py
remove t-w1064-ms-{020, 028} and t-yosemite-r7-{110, 280, 349, 426}
Change the username for Windows and Linux
> Update the client.py

- client.py
> update ldap for linux hosts

- client.py
> add new category stdio linux

- README.md
- client.py
add new worker for gecko-t-linux-talos-tw and update README file with new command
> add new worker for gecko-t-linux-talos-tw and update README file

- client.py
- scanner-v.sh
- scanner.sh
add t-yosemite-r7-246 as loaner for dhouse and two automation scripts
> add t-yosemite-r7-246 as loaner for dhouse and two automation scripts

- client.py
add yosemite: 255,365,367 and linux 358 all with stdio
> add yosemite: 255,365,367 and linux 358 all with stdio

- menu.sh
> add some sub menus to menu.sh

- client.py
- menu.sh
Add some minor changes to menu.sh. Add OSX 223, 333 and WIN 465
> Add some minor changes to menu.sh. Add OSX 223, 333 and WIN 465

- client.py
add win machines 318, 320, 321, 322, 323, 324, 345
> add win machines 318, 320, 321, 322, 323, 324, 345

- client.py
> add t-yosemite-r7-323

- client.py
t-yosemite-r7-393 the machine is repurposed
> t-yosemite-r7-393 the machine is repurposed

- Automation/push.sh
- menu.sh
I have created a script and added it as option into menu.sh to also make it easier to push changes into the repository. 
I have also tested it on one of repos and it works as designed.
> add new option in menu and script for push changes to repo

- client.py
Modified linux and linuxtw range and add 581 to 585 windows machines as loaner for markco
> Modified linux and linuxtw range and add 5 windows machines for markco

- client.py
- menu.sh
made some minor changes to menu and removed machines that were no longer with issues
> made some minor changes to menu and removed machines

- Automation/menu.py
- client.py
Add the new menu.py to fix the issue reported by Travis with the first PR.
> Trying to fix the previous PR.  (menu.py)

- client.py
removed osx 042, 050, 063, 098, 225, 333, 367, 436, 451
added osx 119
removed w10 211, 214, 581
> Cleaned up the old workers

- client.py
Add linux64-ms-313, 392, 401, 402, 405, 481, 540 to other issue (stuck at Reboot Process)
> Add linux64-ms-313, 392, 401, 402, 405, 481, 540 to other issue 

- README.md
- client.py
- twc_modules/configuration.py
- twc_modules/main_menu.py
Add a new parameter "-p" and implement the logic for the persistent menu.
Update README.md with the last run option added.
> Implement the persistent menu.
